### ISSUE TITLE
Pre-Release Checklist.

### ISSUE THREAD

**Issue by GrayHatter** [TokTok/c-toxcore#402]
The following is the list containing all suggestions for drafting a release. The people assigned to each release (the pull that modifies the version numbers), should go though the list in order. And verify each step by hand.

GitHub makes checking list items easy for contributors, so each person who wants to review can copy this list and create a GitHub comment, working their way thorough the list. The intent of this list is to ensure that nothing we're aware of (or should be aware of) ships broken.

- [ ] Open and scan every Travis-CI build verifying that there are NO failed tests (including allowed failures)
- [ ] Read through all Issues, and pulls, making sure that any closed issues have an associated pull, or were closed correctly.
- [ ] Verify that no new actual issues were detected in the static analysers (cppcheck & scan-build links needed)

Any exceptions need to be enumerated, and explained.

**Comment by GrayHatter** [comment]
HIGHLIGHT ALL THE PEOPLE!!!

@TokTok/contributors

**Comment by cebe** [comment]
> Open and scan every Travis-CI build verifying that there are NO failed tests (including allowed failures)

that should be done on the build that runs for the release PR commit.

> Read through all Issues, and pulls, making sure that any closed issues have an associated pull, or were closed correctly.

"Read through" is a bit too much, "briefly go over all issues and pulls" makes more sense.

**Comment by GrayHatter** [comment]
Agreed, I meant scan through. Just enough make sure each was closed/merged correctly.

**Comment by nurupo** [comment]
Here are links to the static analyzers running on Jenkins
- [cppcheck](https://build.tox.chat/job/libtoxcore-toktok_analyze_cppcheck/)
- [scan-build](https://build.tox.chat/job/libtoxcore-toktok_analyze_scan-build/)

For cppcheck you can just go over jobs and see if any + (positive) delta was introduced. New things are highlighted in red, e.g. https://build.tox.chat/job/libtoxcore-toktok_analyze_cppcheck/55/cppcheckResult/.

For scan-build it's harder, as it doesn't show delta and doesn't highlight anything, so you'd have to diff or something.

**Comment by Zer0-One** [comment]
> (including allowed failures)
If they ultimately aren't allowed, why do we have "allowed failures" in the first place?

**Comment by GrayHatter** [comment]
@Zer0-One they aren't reason to block a pull. But they still need human eyes before they're merged into a release. I.e. it's allowed to fail, but only with human approval.

**Comment by dvor** [comment]
> Open and scan every Travis-CI build verifying that there are NO failed tests (including allowed failures)

I also think that this step should be automated.

>  Verify that no new actual issues were detected in the static analysers (cppcheck & scan-build links needed)

Can this be automated as well? E.g. fail only if new issues were introduced compared to previous release.

**Comment by GrayHatter** [comment]
> I also think that this step should be automated.

Yeah, we tried, that, but if a human would have looked at the allowed failures, we wouldn't have almost shipped a version that was unable to compile on OSX. We've since fixed one of the issues, but the real problem is that no one bothered to even look at the failed build assuming it was just the "tests that always fail". Clearly another issue we need to deal with, but this is important too.

**Comment by cebe** [comment]
> tests that always fail

such thing should not exist, if there is such a test, make an issue about it and keep it commented out until fixed so the rest of the tests are still considered when checking PRs.
"allow faliures" feature only makes sense if you do not care about a platform yet because support is experimental.

**Comment by iphydf** [comment]
@robinlinden has a checklist.
